#!/bin/bash

path = "/Test\ Files"

for i in {1..4}
do
	./tokenizer < $path/test.tokenizer.input.0$i | diff - $path/test.tokenizer.output.0$i
done

for i in {1..4}
do
	./parser < $path/test.parser.input.0$i | diff - $path/test.parser.output.0$i
done

for i in {1..9}
do
	./interpreter < $path/test.eval.input.0$i | diff - $path/test.eval.output.0$i
done

for i in {10..13}
do
	./interpreter < $path/test.eval.input.$i | diff - $path/test.eval.output.$i
done
