#!/bin/bash

testPath="Test-Files"
echo $testPath
for i in {1..4}
do
	./tokenizer < $testPath/test.tokenizer.input.0$i | diff - $testPath/test.tokenizer.output.0$i
done

for i in {1..4}
do
	./parser < $testPath/test.parser.input.0$i | diff - $testPath/test.parser.output.0$i
done

for i in {1..9}
do
	./interpreter < $testPath/test.eval.input.0$i | diff - $testPath/test.eval.output.0$i
done

for i in {10..13}
do
	./interpreter < $testPath/test.eval.input.$i | diff - $testPath/test.eval.output.$i
done
